# Generated by Django 6.0 on 2025-12-26 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('motivo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('field_0', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id_receita', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('field_0', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('cc', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('data_nascimento', models.DateField()),
                ('morada', models.CharField(max_length=200)),
                ('telefone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exames',
            fields=[
                ('receita_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='workshop.receita')),
                ('field_0', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
            bases=('workshop.receita',),
        ),
        migrations.CreateModel(
            name='ItemMedicacao',
            fields=[
                ('field_0', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('dose', models.CharField(blank=True, max_length=100)),
                ('quantidade', models.IntegerField(default=1)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workshop.pessoa')),
                ('numero_medico', models.BigIntegerField(unique=True)),
                ('especialidade', models.CharField(max_length=100)),
            ],
            bases=('workshop.pessoa',),
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workshop.pessoa')),
                ('numero_seguranca_social', models.BigIntegerField(unique=True)),
                ('data_registo', models.DateField(auto_now_add=True)),
            ],
            bases=('workshop.pessoa',),
        ),
        migrations.CreateModel(
            name='ItemExames',
            fields=[
                ('field_0', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('resultados', models.TextField(blank=True)),
                ('exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.exame')),
                ('exames', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.exames')),
            ],
        ),
        migrations.AddField(
            model_name='exames',
            name='exames',
            field=models.ManyToManyField(through='workshop.ItemExames', to='workshop.exame'),
        ),
        migrations.CreateModel(
            name='Medicacao',
            fields=[
                ('receita_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='workshop.receita')),
                ('field_0', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('medicamentos', models.ManyToManyField(through='workshop.ItemMedicacao', to='workshop.medicamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.paciente')),
            ],
            bases=('workshop.receita',),
        ),
        migrations.AddField(
            model_name='itemmedicacao',
            name='medicacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.medicacao'),
        ),
        migrations.CreateModel(
            name='MedicoConsulta',
            fields=[
                ('field_0', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=50)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.consulta')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.medico')),
            ],
        ),
        migrations.AddField(
            model_name='medico',
            name='consultas',
            field=models.ManyToManyField(through='workshop.MedicoConsulta', to='workshop.consulta'),
        ),
        migrations.AddField(
            model_name='exames',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.paciente'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='workshop.paciente'),
        ),
    ]
